name: Auto Deploy

on: 
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@main
        with:
          node-version: '14'
      - name: Install Hexo
        run: |
          npm install hexo-cli -g
          npm install
      - name: Load Config
        env: 
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: |
          echo "_config.next.yml\n"
          echo "$CLIENT_ID 123"
          cat _config.next.yml
      - name: Deploy Hexo
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          git config --global user.email "cn-traveler@qq.com"
          git config --global user.name "CN-traveler"
          hexo clean
          hexo deploy
  sync:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Sync Gitee
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        uses: wearerequired/git-mirror-action@master
        with:
          source-repo: git@github.com:Kuiba-Wiki/Kuiba-Wiki.github.io.git
          destination-repo: git@gitee.com:kuiba-wiki/kuiba-wiki.git
  update:
    needs: sync
    runs-on: ubuntu-latest
    steps:
      - name: Update Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          gitee-username: ${{ secrets.GITEE_USERNAME }}
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: kuiba-wiki/kuiba-wiki
          branch: page